# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform syncstorage-rs-docker installation tasks
  when: syncstorage_rs_docker_enabled | bool
  tags:
    - setup-all
    - setup-yourls
    - install-all
    - install-yourls
  block:
    - name: Validate syncstorage-rs-docker configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install syncstorage-rs-docker
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform syncstorage-rs-docker uninstallation tasks
  when: not syncstorage_rs_docker_enabled | bool
  tags:
    - setup-all
    - setup-yourls
  block:
    - name: Uninstall syncstorage-rs-docker
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
