# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "syncstorage_rs_docker_environment_variable_database_host_port", "new": "syncstorage_rs_docker_database_mysql_port" }
    - { "old": "syncstorage_rs_docker_environment_variable_mysql_password", "new": "syncstorage_rs_docker_database_mysql_password" }
    - { "old": "syncstorage_rs_docker_environment_variable_database_hostname", "new": "syncstorage_rs_docker_database_mysql_hostname" }
    - { "old": "syncstorage_rs_docker_environment_variable_database_port", "new": "syncstorage_rs_docker_database_mysql_port" }
    - { "old": "syncstorage_rs_docker_environment_variable_database_username", "new": "syncstorage_rs_docker_database_mysql_username" }
    - { "old": "syncstorage_rs_docker_environment_variable_database_password", "new": "syncstorage_rs_docker_database_mysql_password" }
    - { "old": "syncstorage_rs_docker_environment_variable_database_name_syncstorage", "new": "syncstorage_rs_docker_database_name_syncstorage" }
    - { "old": "syncstorage_rs_docker_environment_variable_database_name_tokenserver", "new": "syncstorage_rs_docker_database_name_tokenserver" }
    - { "old": "syncstorage_rs_docker_http_header_content_permission_policy", "new": "syncstorage_rs_docker_http_header_permissions_policy" }

- name: Fail if required syncstorage-rs-docker settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - syncstorage_rs_docker_uid
    - syncstorage_rs_docker_gid
    - syncstorage_rs_docker_hostname
    - syncstorage_rs_docker_path_prefix
    - syncstorage_rs_docker_container_network
    - syncstorage_rs_docker_database_mysql_password
    - syncstorage_rs_docker_environment_variable_sync_master_secret
    - syncstorage_rs_docker_environment_variable_metrics_hash_secret

- name: Run if Traefik is enabled
  when: syncstorage_rs_docker_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for syncstorage-rs-docker are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - syncstorage_rs_docker_container_labels_traefik_hostname
        - syncstorage_rs_docker_container_labels_traefik_path_prefix

    - name: Fail if syncstorage_rs_docker_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          syncstorage_rs_docker_container_labels_traefik_path_prefix (`{{ syncstorage_rs_docker_container_labels_traefik_path_prefix }}`) must be `/`.
          syncstorage-rs-docker does not support hosting under a subpath yet.
      when: "syncstorage_rs_docker_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `syncstorage_rs_docker_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if syncstorage_rs_docker_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          syncstorage_rs_docker_container_labels_traefik_path_prefix (`{{ syncstorage_rs_docker_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/syncstorage-rs-docker`).
      when: "syncstorage_rs_docker_container_labels_traefik_path_prefix != '/' and syncstorage_rs_docker_container_labels_traefik_path_prefix[-1] == '/'"
